### ISSUE TITLE
DevForum link is filtered in description

### ISSUE THREAD

**Issue by TyNoOutlet** [FlynnFarrow/FolderTool#4]
![image](https://user-images.githubusercontent.com/74572291/125517954-7dd241df-9cd6-4bd2-811e-a55a0ca9bbc4.png)

Make sure to make the link something like:

https://devforum.roblox.com/t/-/1345549

If that doesn't work, try just doing:

https://devforum.roblox.com/t/v0-2-foldertool-group-selected-items-into-a-folder/

**Comment by FlynnFarrow** [comment]
Will fix that later today

**Comment by FlynnFarrow** [comment]
Just fixed it, thanks Ty
